name: Build OpenCV.js

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        pip install numpy

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: '3.1.51'
        no-cache: true

    - name: Verify Emscripten Setup
      run: |
        source /home/runner/emsdk/emsdk_env.sh
        echo "EMSCRIPTEN = $EMSCRIPTEN"
        emcc --version

    - name: Clone OpenCV
      run: |
        git clone --depth 1 --branch 4.9.0 https://github.com/opencv/opencv.git
        cd opencv
        ls -la

    - name: Build OpenCV.js
      run: |
        # Source Emscripten environment
        source /home/runner/emsdk/emsdk_env.sh
        
        cd opencv
        python ./platforms/js/build_js.py build_js --build_wasm --emscripten_dir=$EMSCRIPTEN
        
        echo "Build completed. Contents of build_js/bin/:"
        ls -la build_js/bin/

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: opencv-js
        path: opencv/build_js/bin/
