name: Build OpenCV.js

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        pip install numpy

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: '3.1.51'
        no-cache: true

    - name: Clone OpenCV
      run: |
        git clone --depth 1 --branch 4.9.0 https://github.com/opencv/opencv.git

    - name: Build OpenCV.js
      shell: bash
      run: |
        # Setup Emscripten
        source /home/runner/emsdk/emsdk_env.sh
        
        cd opencv
        mkdir -p build_js
        cd build_js
        
        echo "Running CMake..."
        emcmake cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DOPENCV_ENABLE_NONFREE=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DBUILD_opencv_apps=OFF \
          -DBUILD_opencv_js=ON \
          -DBUILD_opencv_python=OFF \
          -DBUILD_TESTS=OFF \
          -DBUILD_PERF_TESTS=OFF \
          -DBUILD_EXAMPLES=OFF \
          ..
        
        echo "Building..."
        make -j2
        
        echo "Build complete. Checking directory structure:"
        pwd
        echo "Current directory contents:"
        ls -la
        echo "Bin directory contents (if exists):"
        ls -la bin/ || echo "bin directory not found"
        echo "Lib directory contents (if exists):"
        ls -la lib/ || echo "lib directory not found"
        echo "Parent directory contents:"
        ls -la ..
        
        # Try to find the JS files
        echo "Looking for JS files:"
        find . -name "*.js"
        echo "Looking for WASM files:"
        find . -name "*.wasm"

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: opencv-js
        path: |
          opencv/build_js/**/*.js
          opencv/build_js/**/*.wasm
        if-no-files-found: warn
