name: Build OpenCV.js

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential python3-pip
        pip install numpy scikit-build

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: '2.0.34'
        no-cache: true

    - name: Clone OpenCV
      run: |
        git clone --depth 1 --branch 4.8.0 https://github.com/opencv/opencv.git

    - name: Build OpenCV.js
      shell: bash
      run: |
        # Setup Emscripten
        source /home/runner/emsdk/emsdk_env.sh
        
        cd opencv
        
        # Use older known-working build command
        python ./platforms/js/build_js.py --build_wasm --cmake_option="-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencv-js
        path: opencv/build_js/bin/
        if-no-files-found: warn
